---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - пользователь должен иметь возможность редактировать корзину - добавлять, удалять товары , увеличивать количество выбранных товаров и продолжить выбирать товары в каталоге
  - после оформления заказа должен быть переход на страницу оплаты товара
  - для каждого заказа выводится общая сумма заказа
  - для каждого заказа есть подробное описание заказа
  - описание товара должно быть на языке соответсвующем версии сайта
  - для каждого товара должна быть кнопка с подробным описанием
